// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4Eav1jXcWP_a4hfD2EZOw15QyY-AcLY',
    appId: '1:96309569022:web:dbb0613fefc9d081e3ccaf',
    messagingSenderId: '96309569022',
    projectId: 'flutter-crud-84484',
    authDomain: 'flutter-crud-84484.firebaseapp.com',
    storageBucket: 'flutter-crud-84484.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFKnD5PsvsgiDyDBNpgjcgE55ilyukFOY',
    appId: '1:96309569022:android:667319dd7a0b3767e3ccaf',
    messagingSenderId: '96309569022',
    projectId: 'flutter-crud-84484',
    storageBucket: 'flutter-crud-84484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX90w1yb5zsHMwo6dh-Nxlc-XmKVagXYQ',
    appId: '1:96309569022:ios:b4ea3fe8c8aa2930e3ccaf',
    messagingSenderId: '96309569022',
    projectId: 'flutter-crud-84484',
    storageBucket: 'flutter-crud-84484.appspot.com',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX90w1yb5zsHMwo6dh-Nxlc-XmKVagXYQ',
    appId: '1:96309569022:ios:cecc6e567eeecee4e3ccaf',
    messagingSenderId: '96309569022',
    projectId: 'flutter-crud-84484',
    storageBucket: 'flutter-crud-84484.appspot.com',
    iosBundleId: 'com.example.firebasecrud.RunnerTests',
  );
}
